workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

version: 2
jobs:
  build:
    working_directory: ~/microblog
    docker:
      - image: circleci/python:3.9.1      # primary container - where job steps are run
        environment:
          DATABASE_URL: postgresql://microblog_admin@localhost/microblogdb?sslmode=disable

      - image: circleci/postgres:13.1     # services container
        environment:
          POSTGRES_DB: microblogdb
          POSTGRES_USER: microblog_admin
          POSTGRES_PASSWORD: "admin123"

    steps:                                # build job
        # check out source code to working directory
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv django-project
            source django-project/bin/activate
            pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "django-project"

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    environment:
      HEROKU_APP: "djangomicroblog" # define env var $HEROKU_APP
      HEROKU_API_KEY: "e846fda7-dac1-4b21-b639-e90228d07326"
    steps:
      - checkout
      - run:
          name:

      - run:
          name: Setup Heroku and Deploy Master
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            # curl https://cli-assets.heroku.com/install.sh | sh
            # git push heroku master
            # heroku run python manage.py migrate
            # sleep 10
            # heroku restart
