version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4

workflows:
  heroku_deploy:
    jobs:
      # Job supplied by this orb.
      - heroku/deploy-via-git:
          post-steps:
            - run: echo "post deployment steps like database migration"
          pre-steps:
            - run: echo "pre deployment steps, i.e., commands to run before deploying"
